# Generated by Django 5.2.17 on 2026-09-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education_alter_mahasiswa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='institusion',
            new_name='institution',
        ),
    ]
